<?php if (function_exists('acf_add_local_field_group')) :

 /**
   * field groups: PM24 Produkte.
   * @version 1.0.0
   */

  acf_add_local_field_group(array(
    'key' => 'group_5efc9612c4bf6',
    'title' => 'PM24-Produkte CPT',
    'fields' => array(
      array(
        'key' => 'field_5ed9f4770ed17',
        'label' => 'Produktangaben',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5ed97beeaf580',
        'label' => 'Sortierungs-Id',
        'name' => 'pm24_product_sortid',
        'type' => 'text',
        'instructions' => 'Muss eingeben werden!',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '00000',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ed9f36e20a0b',
        'label' => 'Preis',
        'name' => 'pm24_product_price',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '0,00',
        'prepend' => '',
        'append' => '€',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5f0354a6c3f69',
        'label' => 'Weiterlesen-Llink',
        'name' => 'pm24_product_morelink',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'url',
      ),
      array(
        'key' => 'field_5ed9f18c62c0a',
        'label' => 'Downloadlink Quelldatei',
        'name' => 'pm24_product_dl_link',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'url',
      ),
      array(
        'key' => 'field_5ed9f1bb62c0b',
        'label' => 'Downloadlink ZIP-Datei',
        'name' => 'pm24_product_dl_zip',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'url',
      ),
      array(
        'key' => 'field_5ed9f39b20a0c',
        'label' => 'Digistore-Link',
        'name' => 'pm24_product_digilink',
        'type' => 'link',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'url',
      ),
      array(
        'key' => 'field_5ee21f3388c57',
        'label' => 'Teaser / Lead Text',
        'name' => 'pm24_product_leadtext',
        'type' => 'textarea',
        'instructions' => 'Kurzfassung Produktbeschreibung / -benefit / Teaser. Wird über dem Inhalt und auf Übersichtsseiten angezeigt.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => 180,
        'rows' => '',
        'new_lines' => 'br',
        'acfe_textarea_code' => 0,
      ),
      array(
        'key' => 'field_5ed9f48f0ed18',
        'label' => 'Digiprodukt-Zuordnung (Rechte)',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5f0ddb5dacb81',
        'label' => 'Lead-Magnet-ID',
        'name' => 'pm24_product_leadmagnet_id',
        'type' => 'number',
        'instructions' => 'Digimemberprodukt-ID. ID des Digimemberprodukts das diesem PM24-Produkt zugeordnet ist.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5ed9f12f62c08',
        'label' => 'Rechte einschließen',
        'name' => 'pm24_product_has',
        'type' => 'text',
        'instructions' => 'Digimemberprodukt-IDs (mit Komma trennen)
IDs der Bundles, die dieses Produkt beinhalten.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ed9f16d62c09',
        'label' => 'Rechte ausschließen',
        'name' => 'pm24_product_has_not',
        'type' => 'text',
        'instructions' => 'Digimemberprodukt-IDs (mit Komma trennen).
IDs der Bundles, die dieses Produkt ausschließen.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ed9f26220a05',
        'label' => 'Produktpaket-Zuordnung',
        'name' => 'pm24_product_package',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5ee21ea32332f',
        'label' => 'Medien (Bilder / Video)',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5ee0b0346942e',
        'label' => 'Vorschaubild',
        'name' => 'pm24_product_img',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'acfe_uploader' => 'wp',
        'acfe_thumbnail' => 0,
        'return_format' => 'id',
        'preview_size' => 'small',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5ee0b14528ce1',
        'label' => 'Bild als featured Image',
        'name' => 'pm24_product_featured_img',
        'type' => 'true_false',
        'instructions' => 'Bild auch als reguläres Beitragsbild nutzen und in den Theme-Templates entsprechend anzeigen.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'message' => '',
        'default_value' => 0,
        'ui' => 0,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5ed9f21b62c0d',
        'label' => 'Video (no Member)',
        'name' => 'pm24_product_video_nologin',
        'type' => 'oembed',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'width' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_5f034be6361d7',
        'label' => 'Video (Produkt nicht gekauft)',
        'name' => 'pm24_product_video_nobuy',
        'type' => 'oembed',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'width' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_5f034bfe361d8',
        'label' => 'Video (Produkt gekauft)',
        'name' => 'pm24_product_video_buy',
        'type' => 'oembed',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'width' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_5ee0b2a0d0805',
        'label' => 'Galerie',
        'name' => 'pm24_product_gallery',
        'type' => 'gallery',
        'instructions' => 'Galerie anlegen, für weitere Vorschaubilder.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'return_format' => 'array',
        'preview_size' => 'medium',
        'insert' => 'append',
        'library' => 'all',
        'min' => '',
        'max' => '',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_5ed9f4b40ed19',
        'label' => 'Optin-Seite',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5ed9f1c962c0c',
        'label' => 'Video für Optin-Seite',
        'name' => 'pm24_product_optin_video',
        'type' => 'oembed',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'width' => '',
        'height' => '',
      ),
      array(
        'key' => 'field_5ed9f33a20a0a',
        'label' => 'Inhalte für Optinseite',
        'name' => 'pm24_product_content_optin',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'pm24_produkte',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'excerpt',
      1 => 'discussion',
      2 => 'comments',
      3 => 'format',
      4 => 'categories',
      5 => 'tags',
      6 => 'send-trackbacks',
    ),
    'active' => true,
    'description' => '',
    'acfe_display_title' => '',
    'acfe_autosync' => array(
      0 => 'php',
      1 => 'json',
    ),
    'acfe_permissions' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5f04519021271',
    'title' => 'PM24-Produkte Dateiformat',
    'fields' => array(
      array(
        'key' => 'field_5f0451b09d2fe',
        'label' => 'Dateiformat-Icon',
        'name' => 'pm24_fileformat_icon',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'acfe_uploader' => 'wp',
        'acfe_thumbnail' => 0,
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'taxonomy',
          'operator' => '==',
          'value' => 'pm24_fileformat',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_permissions' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5f045c5f0c9e0',
    'title' => 'PM24-Produkte Dateityp',
    'fields' => array(
      array(
        'key' => 'field_5f045c5f11895',
        'label' => 'Labelfarbe',
        'name' => 'pm24_doctype_labelcolor',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'acfe_permissions' => '',
        'default_value' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'taxonomy',
          'operator' => '==',
          'value' => 'pm24_doctype',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_permissions' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

endif;